### ISSUE TITLE
Improving performance when scaling

### ISSUE THREAD

**Issue by ErezBinyamin** [BarakBinyamin/PopulationCount#2]
I downloaded and simulated this project with your testbench, but I noticed that the larger bit width numbers took more clock cycles to complete. This does not make intuitive sense to me, could you explain why this is happening?

**Comment by BarakBinyamin** [comment]
That's a great question! Actually at the time I created this, I was unaware of the scale in which pipelining was helpful. The registers between OP units are in fact not needed, and removing them would fix the clock delay you are seeing
